name: Deploy about.html to GitHub Pages

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Copy the file to the root of the Pages deployment
    - name: Set up deployment folder
      run: |
        mkdir -p public
        cp output/about.html public/index.html

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
